### ISSUE TITLE
IOS application. Library not loaded: @rpath/FreSwift.framework

### ISSUE THREAD

**Issue by Gol-Ant** [tuarua/AdMob-ANE#10]
Hello. We used this ane in clear project under Idea Intellij with AIR 28. 
As a result, the application crashes with an error when running on ios.
Code not found framework.
How to fix this bug?

Error:
Dyld Error Message:
Dyld Message: Library not loaded: @rpath/FreSwift.framework/FreSwift
  Referenced from: /var/containers/Bundle/Application/...ApplicationName.app/ApplicationName

Reason: image not found
  Dyld Version: 390.7

**Comment by tuarua** [comment]
Read the README
https://github.com/tuarua/AdMob-ANE#dependencies-1

Run the example provided first.

**Comment by Gol-Ant** [comment]
This dependencies need to rebuild ANE or for build application? 
Also, I use Idea Intellij by windows and I can't use code for Xcode.
Can I use only release AdMobANE.ane?

Maybe I need add dependencies for other ane?

**Comment by tuarua** [comment]
> This dependencies need to rebuild ANE or for build application?

They are needed to build the application.

> Can I use only release AdMobANE.ane?

No

The dependencies in ios_dependencies.zip are required. It contains 2 frameworks and Apples Swift libraries.
Unfortunately I don't support Windows - even to use the ANE. You need to use a mac.
