### ISSUE TITLE
Crash on iOS Simulator

### ISSUE THREAD

**Issue by dr-andy** [tuarua/AdMob-ANE#16]
When I run your example on iOS Simulator app crashes when showing interstitial ad. Unfortunately there is no stack trace. Banner and Rewarded ads work without any issues. Only problem is Rewarded video ads are rotated in Landscape. Using AIR SDK 30 Beta.

Jun 14 11:13:57 --- com.apple.CoreSimulator.SimDevice.6E6E6A64-B41B-4478-9753-D21C6E3FB026[3930] (com.apple.WebKit.Networking.05947120-675C-47B1-96AF-17D63F097B21[4029]): Service exited with abnormal code: 1
Jun 14 11:13:57 --- launchd_sim[3930]: BUG in libdispatch client: kevent[mach_recv] monitored resource vanished before the source cancel handler was invoked
Jun 14 11:13:57 --- com.apple.CoreSimulator.SimDevice.6E6E6A64-B41B-4478-9753-D21C6E3FB026[3930] (com.apple.WebKit.Networking.0C5B91C1-AB91-4341-A263-2886D2546EC4[4032]): Service exited with abnormal code: 1
Jun 14 11:13:57 --- com.apple.CoreSimulator.SimDevice.6E6E6A64-B41B-4478-9753-D21C6E3FB026[3930] (com.apple.WebKit.WebContent.EAF0A812-3287-4924-BC52-A4CF27968891[4028]): Service exited with abnormal code: 1
Jun 14 11:13:57 --- com.apple.CoreSimulator.SimDevice.6E6E6A64-B41B-4478-9753-D21C6E3FB026[3930] (com.apple.WebKit.WebContent.915B2589-DBAB-456D-825F-B9C18F642077[4031]): Service exited with abnormal code: 1

**Comment by tuarua** [comment]
Everything is working fine for me for all ad types.
Can you give me more details on your: 
- simulator version
- OSX version
- Xcode version 
- your IDE

![image](https://user-images.githubusercontent.com/12083217/41438879-b8af005e-7020-11e8-9efe-3262fb7b56d6.png)

**Comment by dr-andy** [comment]
Simulator Version 10.0 (SimulatorApp-851.2 CoreSimulator-518.21), iOS 11.3
OSX 10.13.4 High Sierra
Xcode Version 9.3.1 (9E501)
IDE is IntelliJ IDEA

**Comment by tuarua** [comment]
I still can't reproduce this.

- Are you using the iPhoneSimulator.sdk from Xcode 9.1 as per the README
(the Simulator in 9.3 won't compile anything with AIR for me)

![image](https://user-images.githubusercontent.com/12083217/41498182-bf1fed88-715e-11e8-8f45-2c053c7aeccb.png)

- Are you using test ads or real ad campaigns ?

**Comment by dr-andy** [comment]
I tried with XCode 9.1 but it's the same, app crashed. For interstitial I used sample ad units "ca-app-pub-3940256099942544/1033173712" and "ca-app-pub-3940256099942544/8691691433". I noticed that it does not crash very rarely and shows the ad.

When I try on a device I get signing error "The application does not have a valid signature" while deploying to device (adhoc). I think this is because of dynamic libraries do not get signed correctly by AIR SDK.

My ADT command using XCode 9.1 iPhoneSimulator.sdk:
/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java -d32 -Dapplication.home=~/Documents/air30_sdk_mac -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.language=en -Duser.region=en -Xmx512m -jar ~/Documents/air30_sdk_mac/lib/adt.jar -package -target ipa-test-interpreter-simulator -storetype PKCS12 -keystore /Applications/IntelliJ IDEA.app/Contents/plugins/flex/lib/temp_keystore.p12 -storepass keystore_password ~/Downloads/AdMob-ANE-master/example/bin-release/sim/AdMob_Sample_iOS.ipa ~/Downloads/AdMob-ANE-master/example/bin-release/sim/Main.xml -platformsdk ~/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -extdir ~/Downloads/AdMob-ANE-master/native_extension/ane -C ~/Downloads/AdMob-ANE-master/example/bin-release/sim AdMob_Sample_iOS.swf -C ~/Downloads/AdMob-ANE-master/example/ios_dependencies/simulator . -C ~/Downloads/AdMob-ANE-master/example/system . -C ~/Downloads/AdMob-ANE-master/example/src Assets.car

**Comment by dr-andy** [comment]
Tested on an iPad and it works there without any issues.
