### ISSUE TITLE
Admob mediation

### ISSUE THREAD

**Issue by ArtyomTukanow** [tuarua/AdMob-ANE#24]
Hi, i'm using Admob-ANE v.2.1.0 and has a problem with myTarget mediation on iOS devices. 
Reward video chash with message:
 -[GADAdReward initWithRewardType:rewardAmount:]: unrecognized selector sent to instance

- GoogleMobileAds v.7.40.0
- MyTargetAdapter v.5.0.1.0
- MyTargetSDK v.5.0.1

**Comment by tuarua** [comment]
The ANE uses Google Mobile Ads SDK 7.36.0
You mention your mediator is using a higher version. 
The error explains that the function GADAdReward.initWithRewardType doesn't exist, likely because the it's a new function.
