### ISSUE TITLE
banner size

### ISSUE THREAD

**Issue by edicsa** [tuarua/AdMob-ANE#30]
Thank You for Ane.
Is it possible to get real size of banner / special height /?
Regards
WOy.

**Comment by tuarua** [comment]
There are no methods to get the height.
Please see the Banner Sizes as listed on these pages:

https://developers.google.com/admob/ios/banner
https://developers.google.com/admob/android/banner

**Comment by edicsa** [comment]
Thank You for answer. 
It sounds ok but maybe it can return size of banner?

**Comment by tuarua** [comment]
> but maybe it can return size of banner?

I'm not sure why you are asking the same question again. I've already given you how you get the size of ad units (including banner). Read the docs I dug out for you
