### ISSUE TITLE
Align error on last android versions

### ISSUE THREAD

**Issue by DezarM** [tuarua/AdMob-ANE#31]
Hello. I have a problem on the latest versions of android.
banner does not align.
i use
`

                adMobANE.banner.hAlign = Align.CENTER;
                adMobANE.banner.vAlign = Align.TOP;
`

this code work on android < 8 version
but if i use android 9 don't work.
can u help? :)

**Comment by tuarua** [comment]
> banner does not align.

I am not seeing any problems.

Please give more details. Read what you wrote and imagine you are me. How would you attempt to fix something with so little information! I am not a magician.

doesn't align where? horizontally or vertically or both?
Which banner size are you using ?
What device are you using?
Are you using portrait or landscape?

**Comment by DezarM** [comment]
sorry)
this's screenshot

![Screenshot_20190929-014849](https://user-images.githubusercontent.com/9121845/65837691-2bc13480-e303-11e9-9620-b23c7311c23f.png)

with code
`
adMobANE.banner.adSize = AdSize.BANNER;
adMobANE.banner.y = Capabilities.screenResolutionY + 450;
`

if i use 

`
adMobANE.banner.hAlign = Align.CENTER;
adMobANE.banner.vAlign = Align.BOTTOM;
`

banner stay on top. not bottom. and not center.

**Comment by tuarua** [comment]
You are trying to use both absolute and relative positioning 
```
adMobANE.banner.y = xxx; //absoloute
adMobANE.banner.vAlign = Align.BOTTOM; //relative
```

so your code is wrong.
You should only **use 1** of .vAlign OR .y but not both

Same goes for .x and hAlign

**Comment by DezarM** [comment]
I'm not use coordinates and alignment together.
BUT.
it's my bad))
i use 

`
adMobANE.init(key,0.5,true,prc,true);
`

where prc my own variable . not starling.)
sorry.
if i use Starling.current.contentScaleFactor - all ok 

thank's for response and your work :)
