### ISSUE TITLE
Can you add the compiled ANE files please?

### ISSUE THREAD

**Issue by goodintention** [tuarua/AdMob-ANE#33]
Hi, I would like to use & donate to this project, currently I'm using Milkman AdMob, but it stopped being updated to support Android 64, Can you add the compiled ANE files please?

**Comment by tuarua** [comment]
Read the readme file.
It tells you how to download the ANE and it's dependencies.

If you don't know how to run the scripts then simply open the files in a browser to see what they do

https://github.com/tuarua/AdMob-ANE/blob/master/example/get_android_dependencies.sh
https://github.com/tuarua/AdMob-ANE/blob/master/example/get_ios_dependencies.sh
