### ISSUE TITLE
AdClicked Event Not Working

### ISSUE THREAD

**Issue by aytanozu** [tuarua/AdMob-ANE#35]
AdMobEvent.ON_CLICKED event not dispatch when user click banner ads.
Also, when I click on the banner, flash events are disabled.
When I click on the back button, the application changes to the background.
This only happens once, then flash events run when reopened

**Comment by tuarua** [comment]
You don't mention any of the following

- Device Operating System
- Device Operating System Version
- AIR version
- Device
- ANE version
- Is the problem reproducible using the sample app.

**Comment by tuarua** [comment]
closing due to lack of response
