### ISSUE TITLE
I can't build for iOS simulator

### ISSUE THREAD

**Issue by mededu** [tuarua/AdMob-ANE#39]
the example project can be run in iOS Device,But can't package to simulator, it show 

`Undefined symbols for architecture x86_64:
  "_strtoul", referenced from:
      __ZN2sw11Synthesizer17encodeInstructionEPKNS_11InstructionE in libRuntimeInterpreter.x86-simulator-air.a(Synthesizer.o)
  "_mprotect", referenced from:
      __Z30AVMPI_makeCodeMemoryExecutablePvmb in libRuntimeInterpreter.x86-simulator-air.a(PosixMMgcPortUtils.o)
  "___strncat_chk", referenced from:
      _Xcode_puny_encodeString in libRuntimeInterpreter.x86-simulator-air.a(puny.o)
  "_ldexp", referenced from:
      _ADFUnpackF32 in libRuntimeInterpreter.x86-simulator-air.a(ADFMathUtils.o)
  "_CFStringAppendCharacters", referenced from:
      _platform_LCMapString in libRuntimeInterpreter.x86-simulator-air.a(gsstring_osx.o)
  "_powf", referenced from:
      __ZN2sw12QuadPipeline10initTablesEv in libRuntimeInterpreter.x86-simulator-air.a(QuadPipeline.o)
  "_kCFNumberFormatterZeroSymbol", referenced from:
      _initCommonOptions in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
      l_switch.table.platform_getLocaleInfo in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
  "_kCFNumberFormatterPositiveSuffix", referenced from:
      _platform_set_numberformat_mode in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
      l_switch.table.platform_getLocaleInfo in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
  "_kCFNumberFormatterPositivePrefix", referenced from:
      _platform_set_numberformat_mode in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
      l_switch.table.platform_getLocaleInfo in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
  "_CFNumberCreate", referenced from:
      _internalSetNumberProperty in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
  "_CFNumberFormatterSetProperty", referenced from:
      _internalSetNumberProperty in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
      _internalSetStringProperty in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
      _initCommonOptions in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
  "_CFBooleanGetValue", referenced from:
      _platform_getLocaleInfoByNumberValue in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
  "_kCFNumberFormatterMaxFractionDigits", referenced from:
      _platform_getLocaleInfoByNumberValue in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
      _initCommonOptions in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
  "_kCFNumberFormatterMinFractionDigits", referenced from:
      _platform_getLocaleInfoByNumberValue in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
      _initCommonOptions in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
  "_CFNumberFormatterCopyProperty", referenced from:
      _platform_getLocaleInfo in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
      _platform_getLocaleInfoByNumberValue in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
      _internalGetNumberProperty in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
      _platform_getNumberFormatGroupingPattern in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
  "_CFNumberFormatterCreate", referenced from:
      _createNumberFormatter in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
  "_kCFNumberFormatterRoundingIncrement", referenced from:
      _createNumberFormatter in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
      _initCurrencyFormat in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
  "_CFLocaleCopyCurrent", referenced from:
      _gslocplat_getDefaultLocaleForOperation in libRuntimeInterpreter.x86-simulator-air.a(gsloc_osx.o)
  "_CFLocaleGetIdentifier", referenced from:
      _gslocplat_getDefaultLocaleForOperation in libRuntimeInterpreter.x86-simulator-air.a(gsloc_osx.o)
  "_CFLocaleCopyAvailableLocaleIdentifiers", referenced from:
      _localeList_open in libRuntimeInterpreter.x86-simulator-air.a(gsloc_osx.o)
  "_dispatch_semaphore_wait", referenced from:
      __ZN2sw11BackoffLock4lockEv in libRuntimeInterpreter.x86-simulator-air.a(Renderer.o)
  "_dispatch_semaphore_create", referenced from:
      __ZN2sw8RendererC2ERNS_7ContextEPNS_7SurfaceE in libRuntimeInterpreter.x86-simulator-air.a(Renderer.o)
  "_CFBundleGetFunctionPointerForName", referenced from:
      _gscolpriv_GetMacOS105DateFormatterFlags in libRuntimeInterpreter.x86-simulator-air.a(gsdat_osx.o)
  "_CFDateFormatterGetFormat", referenced from:
      _platform_getPattern in libRuntimeInterpreter.x86-simulator-air.a(gsdat_osx.o)
  "_kCFDateFormatterCalendar", referenced from:
      _platform_gsdat_getAttribute in libRuntimeInterpreter.x86-simulator-air.a(gsdat_osx.o)
  "_CFCalendarGetFirstWeekday", referenced from:
      _platform_gsdat_getAttribute in libRuntimeInterpreter.x86-simulator-air.a(gsdat_osx.o)
  "_kCFDateFormatterWeekdaySymbols", referenced from:
      _gsSymbolType_to_platformProperty in libRuntimeInterpreter.x86-simulator-air.a(gsdat_osx.o)
  "_kCFNumberFormatterDecimalSeparator", referenced from:
      _platform_init_GNFoptions in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
      l_switch.table.platform_getLocaleInfo in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
  "_kCFDateFormatterShortWeekdaySymbols", referenced from:
      _gsSymbolType_to_platformProperty in libRuntimeInterpreter.x86-simulator-air.a(gsdat_osx.o)
  "_CFCalendarCreateWithIdentifier", referenced from:
      _platform_format in libRuntimeInterpreter.x86-simulator-air.a(gsdat_osx.o)
      _gslocplat_findBestFitForOperation in libRuntimeInterpreter.x86-simulator-air.a(gsloc_osx.o)
  "_CFCalendarSetTimeZone", referenced from:
      _platform_format in libRuntimeInterpreter.x86-simulator-air.a(gsdat_osx.o)
  "_CFDateFormatterCreateStringWithAbsoluteTime", referenced from:
      _platform_format in libRuntimeInterpreter.x86-simulator-air.a(gsdat_osx.o)
  "_kCFDateFormatterShortMonthSymbols", referenced from:
      _gsSymbolType_to_platformProperty in libRuntimeInterpreter.x86-simulator-air.a(gsdat_osx.o)
  "___memcpy_chk", referenced from:
      _compile_branch in libRuntimeInterpreter.x86-simulator-air.a(pcre2_compile.o)
  "_srand", referenced from:
      __ZN9Context3D15RenderStageNULL12BlitToCanvasEP6Canvas in libRuntimeInterpreter.x86-simulator-air.a(Context3DNULL.o)
      __Z16H263CompressOpenPPvii in libRuntimeInterpreter.x86-simulator-air.a(CompressFrame.o)
  "_rand", referenced from:
      __ZN9Context3D15RenderStageNULL12BlitToCanvasEP6Canvas in libRuntimeInterpreter.x86-simulator-air.a(Context3DNULL.o)
      __Z17ResetIntraCounteriPi in libRuntimeInterpreter.x86-simulator-air.a(encmisc.o)
     (maybe you meant: __ZN10AIR_SQLite18sqlite3_randomnessEiPv, __ZN7avmplus8NativeID25Math_random_sampler_thunkEPNS_9MethodEnvEjPx 
, __ZN7avmplus8NativeID19Number_random_thunkEPNS_9MethodEnvEjPx 
, __ZN7avmplus8NativeID27Number_random_sampler_thunkEPNS_9MethodEnvEjPx 
, __ZN7avmplus8NativeID17Math_random_thunkEPNS_9MethodEnvEjPx 
)
  "_CFStringCompare", referenced from:
      __ZN8OSXProxy24GetProxyServerForUrlImplEPKcibR11FlashStringRi in libRuntimeInterpreter.x86-simulator-air.a(OSXProxy.o)
  "_CFRunLoopRemoveSource", referenced from:
      __ZN8OSXProxy8FinalizeEv in libRuntimeInterpreter.x86-simulator-air.a(OSXProxy.o)
  "_SSLWrite", referenced from:
      __ZN20PlatformSecureSocket8SendDataEPKci in libRuntimeInterpreter.x86-simulator-air.a(CTSecureSocket.o)
  "_SSLRead", referenced from:
      __ZN20PlatformSecureSocket7ReceiveEPci in libRuntimeInterpreter.x86-simulator-air.a(CTSecureSocket.o)
  "_SSLClose", referenced from:
      __ZN20PlatformSecureSocket5CloseEv in libRuntimeInterpreter.x86-simulator-air.a(CTSecureSocket.o)
  "_SSLGetNumberSupportedCiphers", referenced from:
      __ZN20PlatformSecureSocket17SetEnabledCiphersEP10SSLContext in libRuntimeInterpreter.x86-simulator-air.a(CTSecureSocket.o)
  "_SSLGetSupportedCiphers", referenced from:
      __ZN20PlatformSecureSocket17SetEnabledCiphersEP10SSLContext in libRuntimeInterpreter.x86-simulator-air.a(CTSecureSocket.o)
  "_SSLSetEnabledCiphers", referenced from:
      __ZN20PlatformSecureSocket17SetEnabledCiphersEP10SSLContext in libRuntimeInterpreter.x86-simulator-air.a(CTSecureSocket.o)
  "_SSLCreateContext", referenced from:
      __ZN20PlatformSecureSocket11InitiateSSLEPKc in libRuntimeInterpreter.x86-simulator-air.a(CTSecureSocket.o)
  "_SSLSetConnection", referenced from:
      __ZN20PlatformSecureSocket11InitiateSSLEPKc in libRuntimeInterpreter.x86-simulator-air.a(CTSecureSocket.o)
  "_kCFNumberFormatterGroupingSize", referenced from:
      _platform_getNumberFormatGroupingPattern in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
      _initCommonOptions in libRuntimeInterpreter.x86-simulator-air.a(gsnum_osx.o)
  "_SSLSetIOFuncs", referenced from:
      __ZN20PlatformSecureSocket11InitiateSSLEPKc in libRuntimeInterpreter.x86-simulator-air.a(CTSecureSocket.o)
  "_SSLSetProtocolVersionMin", referenced from:
      __ZN20PlatformSecureSocket11InitiateSSLEPKc in libRuntimeInterpreter.x86-simulator-air.a(CTSecureSocket.o)
  "_CFDateFormatterCopyProperty", referenced from:
      _platform_countSymbols in libRuntimeInterpreter.x86-simulator-air.a(gsdat_osx.o)
      _platform_getSymbols in libRuntimeInterpreter.x86-simulator-air.a(gsdat_osx.o)
      _platform_gsdat_getAttribute in libRuntimeInterpreter.x86-simulator-air.a(gsdat_osx.o)
  "_SSLSetPeerDomainName", referenced from:
      __ZN20PlatformSecureSocket11InitiateSSLEPKc in libRuntimeInterpreter.x86-simulator-air.a(CTSecureSocket.o)
  "_SecItemDelete", referenced from:
      __ZN21CTEncryptedLocalStore10removeItemEPKcS1_jS1_jS1_j in libRuntimeInterpreter.x86-simulator-air.a(CTEncryptedLocalStore.o)
      __ZN21CTEncryptedLocalStore5resetEPKcjS1_j in libRuntimeInterpreter.x86-simulator-air.a(CTEncryptedLocalStore.o)
  "_kSecReturnData", referenced from:
      __ZN21CTEncryptedLocalStore7getItemEPKcS1_jS1_jS1_jRPhRjS3_S4_ in libRuntimeInterpreter.x86-simulator-air.a(CTEncryptedLocalStore.o)
  "_kSecAttrLabel...

ADT command line:
/Applications/IntelliJ IDEA.app/Contents/jbr/Contents/Home/bin/java -Dapplication.home=/Volumes/WD1Tssd/SystemSoft/AIRSDK_MacOS -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.language=en -Duser.region=en -Xmx512m -jar /Volumes/WD1Tssd/SystemSoft/AIRSDK_MacOS/lib/adt.jar -package -target ipa-test-interpreter-simulator -storetype PKCS12 -keystore /Users/zhouhua/Library/Application Support/JetBrains/IntelliJIdea2020.2/plugins/flex/lib/temp_keystore.p12 -storepass keystore_password /Users/zhouhua/Downloads/AdMob-ANE-master/example/bin-release/sim/admob_is_sim.ipa /Users/zhouhua/Downloads/AdMob-ANE-master/example/bin-release/sim/admob_is_sim-ios-descriptor.xml -platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk -extdir /Users/zhouhua/Downloads/AdMob-ANE-master/example/extensions -C /Users/zhouhua/Downloads/AdMob-ANE-master/example/bin-release/sim admob_is_sim.swf -C /Users/zhouhua/Downloads/AdMob-ANE-master/example/ios_dependencies/simulator . -C /Users/zhouhua/Downloads/AdMob-ANE-master/example/system . -C /Users/zhouhua/Downloads/AdMob-ANE-master/example/src Assets.car`

Thank you , Please help me to solve the problem, I need update my app ,before 2020.12, very thanks!

**Comment by tuarua** [comment]
You are building for simulator but pointing at the device SDK eg `iPhoneOS.platform`
`-platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk
`
Try using the Simulator SDK
`-platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk`

**Comment by mededu** [comment]
Thank you ,last issues is my fault. But I meet a new problem.
I download the release or use the git clone example project.  I can package for iOS simulator now, but when it run ,always show error, the app  crashed with a slash in a second.  Can you help me? I just air-tools install and change the air sdk path, no code changed.  

![截屏2020-10-06 上午12 12 21](https://user-images.githubusercontent.com/1393721/95105130-49707780-0769-11eb-89be-d60afdebfe0c.png)

**Comment by tuarua** [comment]
If you are using the Simulator this is an open AIR bug
See Gamua/Adobe-Runtime-Support#387

Harman are due to release a new version soon with updates for iOS.
Hopefully they will fix it.

**Comment by tuarua** [comment]
This should be fixed in AIR SDK version 33.1.1.406+

![image](https://user-images.githubusercontent.com/12083217/114270396-fd4a0c80-9a03-11eb-9aad-9dc7609ead62.png)
